In [97]:
import numpy as np
import pandas as pd

np.random.seed(29)


1. How likely is it that you roll doubles when rolling two dice?

In [23]:
outcomes = [1,2,3,4,5,6]
n_trials = 2
n_simulations = 10_000

In [111]:
rolls = np.random.choice(outcomes,(n_simulations, n_trials,))
rolls

array([[5, 4, 5, ..., 5, 5, 2],
       [3, 4, 3, ..., 1, 5, 5],
       [5, 4, 6, ..., 5, 2, 5],
       ...,
       [3, 5, 6, ..., 1, 3, 1],
       [4, 2, 3, ..., 3, 4, 1],
       [6, 3, 2, ..., 6, 5, 2]])

In [115]:
df_rolls = pd.DataFrame(rolls)
df_rolls.head()

0     1     2     3     4     5     6     7     8     9     ...  9990  \
0     5     4     5     5     1     1     6     4     6     1  ...     5   
1     3     4     3     3     6     1     2     6     5     6  ...     3   
2     5     4     6     6     1     4     5     1     3     6  ...     2   
3     1     4     3     5     3     3     3     3     6     3  ...     5   
4     2     6     1     3     6     5     4     6     2     4  ...     2   

   9991  9992  9993  9994  9995  9996  9997  9998  9999  
0     2     6     3     1     4     3     5     5     2  
1     1     4     2     5     5     3     1     5     5  
2     5     3     3     6     2     5     5     2     5  
3     5     3     1     1     2     6     2     1     5  
4     6     2     4     1     4     5     4     2     1  

[5 rows x 10000 columns]

In [116]:
(df_rolls[0] == df_rolls[1]).mean()

0.1647

2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [117]:
outcomes = ['H','T']
n_trials = 8
n_simulations = 10_000

In [118]:
three_heads = np.random.choice(outcomes, (n_simulations, n_trials))

In [119]:
((three_heads == "H").sum(axis=1) == 3).mean()

0.2244

What is the probability of getting more than 3 heads?

In [120]:
((three_heads == "H").sum(axis=1) > 3).mean()

0.6287

3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [17]:
n_sim_billboards = nrows = 10_000
n_boards = ncols = 2 
p_data_science = .25

In [18]:
data = np.random.random((nrows,ncols))
data

array([[0.51036449, 0.22892431],
       [0.49224936, 0.92355859],
       [0.63017188, 0.72776579],
       ...,
       [0.23403889, 0.54977971],
       [0.3471889 , 0.97657646],
       [0.546266  , 0.59416714]])

In [19]:
billboard = (data <= p_data_science)
(billboard.sum(axis=1) == 2).mean()

0.0649

4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [25]:
trials_4 = 10_000
mean = 3
std = 1.5
days_4 = 5

In [39]:
pop_tarts = np.random.normal(mean, std, (trials_4, days_4))
pop_tarts

array([[ 4.68899437,  2.6756616 ,  3.39512131,  0.87045861,  4.01475447],
       [ 3.19698286,  6.11904905,  4.55929297,  2.6521373 ,  5.3352225 ],
       [ 1.47517336,  4.38739502,  5.33336319,  3.61011211,  3.29730779],
       ...,
       [ 5.52309748,  2.4387194 ,  4.03023755,  0.07696409,  1.78096784],
       [ 2.62509817,  5.91481937,  2.4753681 ,  4.63182411,  2.65654557],
       [ 3.05397509, -0.11430862,  4.74123596,  3.83454333,  2.78390769]])

In [42]:
pop_tarts_a = pop_tarts.sum(axis=1)
pop_tarts_a

array([15.64499035, 21.86268468, 18.10335147, ..., 13.84998637,
       18.30365531, 14.29935345])

In [43]:
(17 - pop_tarts_a >= 1).mean()

0.6213

5. Compare Heights
Men have an average height of 178 cm and standard deviation of 8cm.

Women have a mean of 170, sd = 6cm.

Since you have means and standard deviations, you can use np.random.normal to generate observations.

In [44]:
mean_men_height = 178
men_std = 8

In [45]:
mean_women_height = 170
women_std = 6

In [47]:
trials = 10_000

In [48]:
men_heights = np.random.normal(mean_men_height, men_std, trials)
men_heights

array([171.12991107, 165.79804099, 183.93699239, ..., 164.7816077 ,
       186.72151715, 178.87522168])

In [50]:
women_heights = np.random.normal(mean_women_height, women_std, trials)
women_heights

array([177.56434115, 166.13632267, 159.84914603, ..., 175.36238098,
       175.69165827, 169.72678246])

In [51]:
(women_heights > men_heights).mean()

0.2176

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [61]:
p_corrupted = 1/250
students = ncols = 50
trials = nrows = 10_000

In [62]:
data = np.random.random((nrows, ncols))
data

array([[0.98263348, 0.67381045, 0.44315353, ..., 0.16615124, 0.91821421,
        0.44222655],
       [0.73467615, 0.11694303, 0.17996408, ..., 0.98573734, 0.93247076,
        0.55579589],
       [0.54193729, 0.51946803, 0.34748914, ..., 0.87767443, 0.18581018,
        0.77845822],
       ...,
       [0.99525826, 0.36479391, 0.32192952, ..., 0.34925864, 0.37654   ,
        0.20030533],
       [0.59824809, 0.59987501, 0.18603805, ..., 0.24025922, 0.99374766,
        0.24135302],
       [0.97171507, 0.21461742, 0.42788527, ..., 0.66620715, 0.32101351,
        0.99982711]])

In [63]:
corrupted = data <= p_corrupted
corrupted

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [64]:
corrupted.sum(axis=1)

array([1, 0, 1, ..., 1, 0, 0])

In [65]:
(corrupted.sum(axis=1) == 0).mean()

0.8197

100 students?

In [66]:
p_corrupted_100 = 1/250
students_100 = ncols_100 = 100
trials = nrows = 10_000

In [67]:
data = np.random.random((nrows, ncols_100))
data

array([[0.00810442, 0.41198   , 0.32954114, ..., 0.49049137, 0.16288112,
        0.4802257 ],
       [0.51534982, 0.76085467, 0.80080464, ..., 0.67341033, 0.93373254,
        0.90076016],
       [0.20121889, 0.52233493, 0.16757199, ..., 0.33723264, 0.81849369,
        0.37929812],
       ...,
       [0.43185658, 0.11497543, 0.9924364 , ..., 0.1388827 , 0.59905708,
        0.4101757 ],
       [0.76711801, 0.51689894, 0.67667994, ..., 0.8585721 , 0.03591773,
        0.88096867],
       [0.7858843 , 0.49171553, 0.60369355, ..., 0.06907438, 0.31618962,
        0.54699545]])

In [68]:
corrupted_100 = data <= p_corrupted
corrupted_100

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [69]:
corrupted_100.sum(axis=1)

array([0, 0, 1, ..., 0, 1, 1])

In [70]:
(corrupted_100.sum(axis=1) == 0).mean()

0.6629

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [71]:
p_corrupted_150 = 1/250
students_150 = ncols_150 = 150

In [72]:
data_150 = np.random.random((nrows, ncols_150))

In [76]:
corrupted_150 = (data_150 <= p_corrupted_150)

In [81]:
(corrupted_150.sum(axis=1) == 0).mean()

In [78]:
1 - (corrupted_150.sum(axis=1) == 0).mean()

0.4538

In [79]:
from scipy import stats

In [80]:
#double checking my work
stats.binom(150,0.004).sf(0)

0.4518483022503269

How likely is it that 450 students all download anaconda without an issue?

In [82]:
students_450 = ncols_450 = 450

In [83]:
data_450 = np.random.random((nrows, ncols_450))

In [84]:
corrupted_450 = (data_450 <= p_corrupted)
(corrupted_450.sum(axis=1) == 0).mean()

0.1686

7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [85]:
n_trials = 10_000
p_foodtruck = .70
days_7 = 3

In [86]:
data_7 = np.random.random((n_trials,days_7))
data_7

array([[0.41845628, 0.59687274, 0.97696196],
       [0.01178332, 0.03197261, 0.24133024],
       [0.80319717, 0.07792901, 0.51694973],
       ...,
       [0.39257664, 0.57862958, 0.437011  ],
       [0.8213894 , 0.80677924, 0.72665692],
       [0.2395986 , 0.50718163, 0.72681392]])

In [87]:
food_truck = (data_7 <= p_foodtruck)
((food_truck).sum(axis=1) == 0).mean()

0.0258

How likely is it that a food truck will show up sometime this week?

In [88]:
days_7_1 = 5

data_7_1 = np.random.random((n_trials,days_7_1))
food_truck = data_7_1 <= p_foodtruck
((food_truck).sum(axis=1) >= 1).mean()

0.9979

8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [89]:
n_trial = 10_000
days_8 = list(range(1,366))

people = 23

In [90]:
data_8 = np.random.choice(days_8,(n_trial,people))
data_8

array([[136,  39, 263, ..., 103, 341, 270],
       [141,   5, 191, ..., 124,  22,  94],
       [269,   5,  76, ..., 162, 146, 120],
       ...,
       [110, 246, 348, ..., 111, 135,  18],
       [ 23, 249, 267, ..., 206, 321,  67],
       [206, 147, 235, ..., 198,  66, 279]])

In [91]:
df_data_8 = pd.DataFrame(data_8)
df_data_8

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     136   39  263  261   93  166  232   88  220  278  ...  125  258   88   
1     141    5  191  291  245  253  151  362  242  151  ...  111  306   98   
2     269    5   76    2   83  226  141   73  334  271  ...  151   53   86   
3     245  362   56  278  123   40  211   61  287  112  ...  353  275  174   
4     213  230  299   13  177  224  343  248  294  334  ...  213  154  179   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  170   14   82  291  337  221  293   84   53  359  ...  241  242  225   
9996  324   99  102  312  111  292  145  318  132   63  ...  340  195  311   
9997  110  246  348  287  249  228  222  164  350  127  ...  250  221  359   
9998   23  249  267  319  351  205  275  221  214  308  ...  299   45  198   
9999  206  147  235  143  306  305  354   74  212  303  ...  276  147    3   

       16   17   18   19   20   21   22  
0     253  277  125  226  103  341  270  
1      46  259  216  230  124   22   94  
2     243  329  346  104  162  146  120  
3     165  160   88  276  119  256  112  
4     128    8  299  273   33  283  186  
...   ...  ...  ...  ...  ...  ...  ...  
9995  233   92   59  305  363  104  185  
9996  261  113  264  100  337  192  224  
9997  356   23  156  191  111  135   18  
9998   42  322  323  274  206  321   67  
9999   35  230  256  183  198   66  279  

[10000 rows x 23 columns]

In [99]:
df_data_8.nunique(axis=1)

0       21
1       22
2       23
3       22
4       21
        ..
9995    23
9996    23
9997    23
9998    23
9999    22
Length: 10000, dtype: int64

In [121]:
df_data_8.nunique(axis=1) < people

0        True
1        True
2       False
3        True
4        True
        ...  
9995    False
9996    False
9997    False
9998    False
9999     True
Length: 10000, dtype: bool

In [122]:
(df_data_8.nunique(axis=1) < people).mean()

0.5071

What if it's 20 people? 

In [131]:
n_trial = 100_000

In [132]:
people_1 = 20

In [133]:
data_8_1 = np.random.choice(days_8,(n_trial,people_1))

In [134]:
df_data_8_1 = pd.DataFrame(data_8_1)

In [135]:
(df_data_8_1.nunique(axis=1) < people_1).mean()

0.41355

40?

In [127]:
people_2 = 40

In [128]:
data_8_2 = np.random.choice(days_8,(n_trial,people_2))

In [129]:
df_data_8_2 = pd.DataFrame(data_8_2)

In [130]:
(df_data_8_2.nunique(axis=1) < people_2).mean()

0.8956